### GET /
GET http://localhost:3000/

### Register User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "tanvir",
  "password": "1234"
}


### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "tanvir",
  "password": "1234"
}